### ISSUE TITLE
Label at the bottom

### ISSUE THREAD

**Issue by breiler** [breiler/ugs_candy_mechanics#1]
Is it possible to have the 'localhost-4200/#' text removed at the bottom left? We couldn't figure out how to stop this from coming up.

**Comment by breiler** [comment]
This comes from the browser and it seems it can't be turned off:
https://support.google.com/chrome/forum/AAAAP1KN0B0FtD7qjochgw/?hl=en&gpf=d/category-topic/chrome/discuss-chrome/FtD7qjochgw

You could try installing another browser

**Comment by cwtait2** [comment]
Ok will do

> This comes from the browser and it seems it can't be turned off:
> https://support.google.com/chrome/forum/AAAAP1KN0B0FtD7qjochgw/?hl=en&gpf=d/category-topic/chrome/discuss-chrome/FtD7qjochgw
> 
> You could try installing another browser
