### ISSUE TITLE
Autorefresh select a file page

### ISSUE THREAD

**Issue by breiler** [breiler/ugs_candy_mechanics#2]
Can this auto-refresh to show new files? At the moment I have to hit F5 to refresh the page

**Comment by breiler** [comment]
@cwtait2 added feature for auto updating file list automatically. The refresh rate is configurable in the environments-file

**Comment by cwtait2** [comment]
@breiler I was trying this out yesterday and was having troubles with chromium on the raspberry pi slowing down and freezing - it often seemed to happen when a new file was added. It didn't seem to happen before like this - do you think refresh rate corresponds to cpu load?
