### ISSUE TITLE
Tab the select file page with new/processed

### ISSUE THREAD

**Issue by breiler** [breiler/ugs_candy_mechanics#3]
Is it possible to have a tabbed bit here? This was in the original doc I sent over but I forgot to follow up on it. - i.e. new and redo files - see below image. Ideally, when a file has been created, it goes to the gcode folder, then when it is finished being done on the machine, it gets put into an oldgcode folder. This way, in a busy scenario the new folder doesn't get clogged up, but still if someone wanted to re-do they could access the file.

**Comment by breiler** [comment]
It was hard to do this in UGS by moving files to it's own folder. Instead I'm trying to use the web browsers function for storing session data. It will store the processed file name when the job is complete and show these in its own tab.

**Comment by cwtait2** [comment]
@breiler looks like this is working in principle, but for some reason now only .gcode files are visible, whereas .tap files (another type of NC file extension we use) doesn't. I had a look through all the updated files but can't find any references to particular file extensions so don't know why all of a sudden .tap files wouldn't be showing up. Any ideas?

**Comment by breiler** [comment]
I tried with a tap-file in the directory (test.tap), and this shows up in the browser.
![image](https://user-images.githubusercontent.com/8962024/64506000-3a08cb80-d2d6-11e9-8e86-027e373ee902.png)

It's also shown in the UI
![image](https://user-images.githubusercontent.com/8962024/64506721-db911c80-d2d8-11e9-91cb-dc9e8cf7fc65.png)

You could try downloading the latest version of UGS:
https://github.com/winder/Universal-G-Code-Sender

**Comment by cwtait2** [comment]
updated UGS and it now shows .tap files!
