### ISSUE TITLE
Error message when stopping job

### ISSUE THREAD

**Issue by breiler** [breiler/ugs_candy_mechanics#8]
Also, we have a little cancel switch when someone opens the machine to stop the job, which turns off the spindle and displays an error message. At the moment the error message doesn't make sense for a novice, so where could we find the source file for that to change it to something a bit more understandable to a new user?

**Comment by breiler** [comment]
Could you post a screenshot of this?

**Comment by cwtait2** [comment]
I don't have an up to date image with the new UX but this is basically it: 
On our controller there is an input pin you can hook up to a button that activates the reset runtime grbl command. This basically stops any job (stops motors and spindle) and also prevents a new one from starting until the button is no longer pressed and the user has acknowledged the error. 
![IMG_20190327_201004](https://user-images.githubusercontent.com/48127049/60689714-42005580-9eb8-11e9-81d1-63a75dde5a64.jpg)

**Comment by breiler** [comment]
Ah, I know where to fix this and this will generally be a good fix for UGS. There have been cases where users have been flooded with these error popups. It's better to display them in the console...

**Comment by breiler** [comment]
Fixed in https://github.com/winder/Universal-G-Code-Sender/pull/1250

**Comment by cwtait2** [comment]
super - @breiler is there a way of changing the text of the error and styling it? So instead of a lot of (to a customer) gibberish it says something like Error - please contact a member of staff, or error - please close the lid and reset. If there is a simple html file we could edit that'd be great.

**Comment by breiler** [comment]
Is there a need for an error message at all?

With the latest version of UGS (not yet built as a nightly build though) the message will only be logged to console.

**Comment by cwtait2** [comment]
Yes, for health and safety for this machine it needs to show some kind of message to a user and needs to get acknowledgement from that user. 
We have 2 switches that 'cancel' feed and turn off the spindle. One is a door release, and the other is a button beside the touchscreen. If something goes wrong and the button is pressed, or the door is opened, it's good practice to have an error message come up to provide that alert to the user so they know to be attentive, and then to also get the user to acknowledge the error. 
At the moment if a cut is being done and it's 'cancelled' the error like the one in the photo comes up which is good, but it'd just be nice to be able to change the text. Understand if this is totally ingrained inUGS though.
